Unable to connect to the database.

se.kth.iv1350.pos.integration.DatabaseConnectionException: Unable to connect to the database.
	at se.kth.iv1350.pos.integration.InventoryHandler.getItemDTO(InventoryHandler.java:43)
	at se.kth.iv1350.pos.controller.Controller.scanItem(Controller.java:69)
	at se.kth.iv1350.pos.view.View.scanItem(View.java:86)
	at se.kth.iv1350.pos.view.View.fakeExecutionRun(View.java:47)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:27)
